name: Build nexus public
run-name: build nexus public
on: [push]
jobs:
  build nexus public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          submodules: recursive
      - run: |
          cd nexus-public
          

