name: Build nexus public
run-name: build nexus public
on: [push]
jobs:
  build-nexus-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          submodules: recursive
      - run: |
          cd nexus-public
          ls
      - run: |
          git fetch --tags
          git tag -l
          git checkout tags/release-3.45.0-01
      - run: |
          ./mvnw clean install

