name: Build nexus public
run-name: build nexus public
on: [push]
jobs:
  build-nexus-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Install JAVA8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'
      - name: get submodule tag
        run: |
          cd nexus-public
          ls
          git fetch --tags
          git tag -l
          git checkout tags/release-3.45.0-01
      - name: Build zip file
        run: |
          cd nexus-public
          java -version
          ./mvnw clean install

